meta_product_name: "Way to Snow"
meta_title: "Way to Snow - find the perfect powder..."
meta_description: "Providing live snow information for 285 ski resorts in Japan"
meta_image: "meta-snowboard.jpg" # should exist in `app/assets/images/`
